version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
